# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: modal-controller CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  modal-controller-CI:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: pnpm install
      run: npm i -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: lint check
      run: pnpm prettier ./src --check && pnpm eslint .
      
    - name: test check
      run: pnpm test

    - name: build check
      run: pnpm build

    - name: Success notification to discord
      uses: sarisia/actions-status-discord@v1.11.0
      if: ${{ success() }}
      with:
        webhook: ${{ secrets.WEBHOOK }}
        title: 'modal-controller CI successfully'
        description: 'modal-controller CI success'
        content: 'success!!!'
        username: 'modal-controller CI'
        url: 'https://github.com/chanwoo00106/modal-controller'
        color: 4CAF50
        avatar_url: ${{ secrets.AVATAR_URL }}

    - name: Failure notification to discord
      uses: sarisia/actions-status-discord@v1.11.0
      if: ${{ failure() }}
      with:
        webhook: ${{ secrets.WEBHOOK }}
        title: 'modal-controller CI failed'
        description: 'modal-controller CI failed'
        content: 'ㅆㅂ...'
        username: 'modal-controller CI'
        url: 'https://github.com/chanwoo00106/modal-controller'
        color: e74c3c
        avatar_url: ${{ secrets.AVATAR_URL }}
